
vip:
  ipav:
    #RestTemplate 最大连接数
    total: 4000
    #RestTemplate 最大路由数
    route: 4000
    #RestTemplate 请求超时时间
    requestTimeout: 60000
    #RestTemplate 连接超时时间
    connectTimeout: 60000
    #RestTemplate 读取超时时间
    readTimeout: 60000
    #Rest是否启用调试
    restDebug: false
